version: '3.8'

services:
  web:
    build: .
    container_name: fastapi_app
    command: [ "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "80" ]
    ports:
      - "80:80"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql+asyncpg://vlone:pass@db:5432/tasks_db

  db:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: tasks_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
